name: FastConfig
author: godfather
main: org.godfather.fastconfig.bukkit.FastConfig
version: 1.0.0

commands:
  configcreate:
    aliases: [ccreate, confcreate]
  configdelete:
    aliases: [cdelete, confdelete]
  configmodify:
    aliases: [cmodify, confmodify, cedit, confedit]
  configreload:
    aliases: [creload, confreload]
  configabort:
    aliases: [cabort, confabort]

permissions:
  fastconfig.create:
    default: false
  fastconfig.delete:
    default: false
  fastconfig.modify:
    default: false
  fastconfig.reload:
    default: false
  fastconfig.abort:
    default: false