name: FastConfig
author: godfather
main: org.godfather.fastconfig.bukkit.FastConfig
version: 1.1.2

commands:
  config:
    aliases: [configuration, yml]

permissions:
  fastconfig.create:
    default: false
  fastconfig.delete:
    default: false
  fastconfig.modify:
    default: false
  fastconfig.reload:
    default: false
  fastconfig.abort:
    default: false
  fastconfig.help:
    default: false